// Copyright lowRISC contributors.
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0
//
// Register Package auto-generated by `reggen` containing data structure

package rv_iopmp_reg_pkg;

  // Address widths within the block
  parameter int BlockAw = 14;

  parameter int N_MDS       = 2;
  parameter int N_RRID      = 32;
  parameter int N_ENTRIES   = 16;

  ////////////////////////////
  // Typedefs for registers //
  ////////////////////////////

  typedef struct packed {
    struct packed {
      logic [23:0] q;
    } vendor;
    struct packed {
      logic [7:0]  q;
    } specver;
  } rv_iopmp_reg2hw_version_reg_t;

  typedef struct packed {
    logic [31:0] q;
  } rv_iopmp_reg2hw_implementation_reg_t;

  typedef struct packed {
    struct packed {
      logic [1:0]  q;
    } mdcfg_fmt;
    struct packed {
      logic [1:0]  q;
    } srcmd_fmt;
    struct packed {
      logic        q;
    } tor_en;
    struct packed {
      logic        q;
    } sps_en;
    struct packed {
      logic        q;
    } user_cfg_en;
    struct packed {
      logic        q;
    } prient_prog;
    struct packed {
      logic        q;
    } rrid_transl_en;
    struct packed {
      logic        q;
    } rrid_transl_prog;
    struct packed {
      logic        q;
    } chk_x;
    struct packed {
      logic        q;
    } no_x;
    struct packed {
      logic        q;
    } no_w;
    struct packed {
      logic        q;
    } stall_en;
    struct packed {
      logic        q;
    } peis;
    struct packed {
      logic        q;
    } pees;
    struct packed {
      logic        q;
    } mfr_en;
    struct packed {
      logic [6:0]  q;
    } md_entry_num;
    struct packed {
      logic [5:0]  q;
    } md_num;
    struct packed {
      logic        q;
    } addrh_en;
    struct packed {
      logic        q;
    } enable;
  } rv_iopmp_reg2hw_hwcfg0_reg_t;

  typedef struct packed {
    struct packed {
      logic [15:0] q;
    } rrid_num;
    struct packed {
      logic [15:0] q;
    } entry_num;
  } rv_iopmp_reg2hw_hwcfg1_reg_t;

  typedef struct packed {
    struct packed {
      logic [15:0] q;
    } prio_entry;
    struct packed {
      logic [15:0] q;
    } rrid_transl;
  } rv_iopmp_reg2hw_hwcfg2_reg_t;

  typedef struct packed {
    logic [31:0] q;
  } rv_iopmp_reg2hw_entryoffset_reg_t;

  typedef struct packed {
    struct packed {
      logic        q;
    } lock;
    struct packed {
      logic        q;
    } ie;
    struct packed {
      logic        q;
    } rs;
    struct packed {
      logic        q;
    } msi_en;
    struct packed {
      logic        q;
    } stall_violation_en;
    struct packed {
      logic [10:0] q;
    } msidata;
  } rv_iopmp_reg2hw_err_cfg_reg_t;

  typedef struct packed {
    struct packed {
      logic        q;
    } v;
    struct packed {
      logic [1:0]  q;
    } ttype;
    struct packed {
      logic        q;
    } msi_werr;
    struct packed {
      logic [3:0]  q;
    } etype;
    struct packed {
      logic        q;
    } svc;
  } rv_iopmp_reg2hw_err_info_reg_t;

  typedef struct packed {
    logic [15:0] q;
  } rv_iopmp_reg2hw_mdcfg_reg_t;

  typedef struct packed {
    struct packed {
      logic        q;
    } lock;
    struct packed {
      logic [30:0] q;
    } md;
  } rv_iopmp_reg2hw_srcmd_en_reg_t;

  typedef struct packed {
    logic [31:0] q;
  } rv_iopmp_reg2hw_srcmd_enh_reg_t;

  typedef struct packed {
    logic [31:0] q;
  } rv_iopmp_reg2hw_entry_addr_reg_t;

  typedef struct packed {
    logic [31:0] q;
  } rv_iopmp_reg2hw_entry_addrh_reg_t;

  typedef struct packed {
    struct packed {
      logic        q;
    } r;
    struct packed {
      logic        q;
    } w;
    struct packed {
      logic        q;
    } x;
    struct packed {
      logic [1:0]  q;
    } a;
    struct packed {
      logic        q;
    } sire;
    struct packed {
      logic        q;
    } siwe;
    struct packed {
      logic        q;
    } sixe;
    struct packed {
      logic        q;
    } sere;
    struct packed {
      logic        q;
    } sewe;
    struct packed {
      logic        q;
    } sexe;
  } rv_iopmp_reg2hw_entry_cfg_reg_t;

  typedef struct packed {
    logic [31:0] q;
  } rv_iopmp_reg2hw_entry_user_cfg_reg_t;

  typedef struct packed {
    struct packed {
      logic        d;
      logic        de;
    } v;
    struct packed {
      logic [1:0]  d;
      logic        de;
    } ttype;
    struct packed {
      logic        d;
      logic        de;
    } msi_werr;
    struct packed {
      logic [3:0]  d;
      logic        de;
    } etype;
    struct packed {
      logic        d;
      logic        de;
    } svc;
  } rv_iopmp_hw2reg_err_info_reg_t;

  typedef struct packed {
    logic [31:0] d;
    logic        de;
  } rv_iopmp_hw2reg_err_reqaddr_reg_t;

  typedef struct packed {
    logic [31:0] d;
    logic        de;
  } rv_iopmp_hw2reg_err_reqaddrh_reg_t;

  typedef struct packed {
    struct packed {
      logic [15:0] d;
      logic        de;
    } rrid;
    struct packed {
      logic [15:0] d;
      logic        de;
    } eid;
  } rv_iopmp_hw2reg_err_reqid_reg_t;

  typedef struct packed {
    logic [31:0] d;
    logic        de;
  } rv_iopmp_hw2reg_err_msiaddr_reg_t;

  typedef struct packed {
    logic [31:0] d;
    logic        de;
  } rv_iopmp_hw2reg_err_msiaddrh_reg_t;

  // Register -> HW type
  typedef struct packed {
    rv_iopmp_reg2hw_version_reg_t version; // [403:372]
    rv_iopmp_reg2hw_implementation_reg_t implementation; // [371:340]
    rv_iopmp_reg2hw_hwcfg0_reg_t hwcfg0; // [339:308]
    rv_iopmp_reg2hw_hwcfg1_reg_t hwcfg1; // [307:276]
    rv_iopmp_reg2hw_hwcfg2_reg_t hwcfg2; // [275:244]
    rv_iopmp_reg2hw_entryoffset_reg_t entryoffset; // [243:212]
    rv_iopmp_reg2hw_err_cfg_reg_t err_cfg; // [211:196]
    rv_iopmp_reg2hw_err_info_reg_t err_info; // [195:187]
    rv_iopmp_reg2hw_mdcfg_reg_t          [N_MDS - 1:0    ] mdcfg; // [186:171]
    rv_iopmp_reg2hw_srcmd_en_reg_t       [N_RRID - 1:0   ] srcmd_en; // [170:139]
    rv_iopmp_reg2hw_srcmd_enh_reg_t      [N_RRID - 1:0   ] srcmd_enh; // [138:107]
    rv_iopmp_reg2hw_entry_addr_reg_t     [N_ENTRIES - 1:0] entry_addr; // [106:75]
    rv_iopmp_reg2hw_entry_addrh_reg_t    [N_ENTRIES - 1:0] entry_addrh; // [74:43]
    rv_iopmp_reg2hw_entry_cfg_reg_t      [N_ENTRIES - 1:0] entry_cfg; // [42:32]
    rv_iopmp_reg2hw_entry_user_cfg_reg_t [N_ENTRIES - 1:0] entry_user_cfg; // [31:0]
  } rv_iopmp_reg2hw_t;

  // HW -> register type
  typedef struct packed {
    rv_iopmp_hw2reg_err_info_reg_t err_info; // [179:166]
    rv_iopmp_hw2reg_err_reqaddr_reg_t err_reqaddr; // [165:133]
    rv_iopmp_hw2reg_err_reqaddrh_reg_t err_reqaddrh; // [132:100]
    rv_iopmp_hw2reg_err_reqid_reg_t err_reqid; // [99:66]
    rv_iopmp_hw2reg_err_msiaddr_reg_t err_msiaddr; // [65:33]
    rv_iopmp_hw2reg_err_msiaddrh_reg_t err_msiaddrh; // [32:0]
  } rv_iopmp_hw2reg_t;

  // Register offsets
  parameter logic [BlockAw-1:0] RV_IOPMP_VERSION_OFFSET = 14'h 0;
  parameter logic [BlockAw-1:0] RV_IOPMP_IMPLEMENTATION_OFFSET = 14'h 4;
  parameter logic [BlockAw-1:0] RV_IOPMP_HWCFG0_OFFSET = 14'h 8;
  parameter logic [BlockAw-1:0] RV_IOPMP_HWCFG1_OFFSET = 14'h c;
  parameter logic [BlockAw-1:0] RV_IOPMP_HWCFG2_OFFSET = 14'h 10;
  parameter logic [BlockAw-1:0] RV_IOPMP_ENTRYOFFSET_OFFSET = 14'h 14;
  parameter logic [BlockAw-1:0] RV_IOPMP_ERR_CFG_OFFSET = 14'h 60;
  parameter logic [BlockAw-1:0] RV_IOPMP_ERR_INFO_OFFSET = 14'h 64;
  parameter logic [BlockAw-1:0] RV_IOPMP_ERR_REQADDR_OFFSET = 14'h 68;
  parameter logic [BlockAw-1:0] RV_IOPMP_ERR_REQADDRH_OFFSET = 14'h 6c;
  parameter logic [BlockAw-1:0] RV_IOPMP_ERR_REQID_OFFSET = 14'h 70;
  parameter logic [BlockAw-1:0] RV_IOPMP_ERR_MSIADDR_OFFSET = 14'h 78;
  parameter logic [BlockAw-1:0] RV_IOPMP_ERR_MSIADDRH_OFFSET = 14'h 7c;
  parameter logic [BlockAw-1:0] RV_IOPMP_MDCFG_OFFSET = 14'h 800;
  parameter logic [BlockAw-1:0] RV_IOPMP_SRCMD_EN_OFFSET = 14'h 1000;
  parameter logic [BlockAw-1:0] RV_IOPMP_SRCMD_ENH_OFFSET = 14'h 1004;
  parameter logic [BlockAw-1:0] RV_IOPMP_ENTRY_ADDR_OFFSET = 14'h 2000;
  parameter logic [BlockAw-1:0] RV_IOPMP_ENTRY_ADDRH_OFFSET = 14'h 2004;
  parameter logic [BlockAw-1:0] RV_IOPMP_ENTRY_CFG_OFFSET = 14'h 2008;
  parameter logic [BlockAw-1:0] RV_IOPMP_ENTRY_USER_CFG_OFFSET = 14'h 200c;

  // Register index
  typedef enum int {
    RV_IOPMP_VERSION,
    RV_IOPMP_IMPLEMENTATION,
    RV_IOPMP_HWCFG0,
    RV_IOPMP_HWCFG1,
    RV_IOPMP_HWCFG2,
    RV_IOPMP_ENTRYOFFSET,
    RV_IOPMP_ERR_CFG,
    RV_IOPMP_ERR_INFO,
    RV_IOPMP_ERR_REQADDR,
    RV_IOPMP_ERR_REQADDRH,
    RV_IOPMP_ERR_REQID,
    RV_IOPMP_ERR_MSIADDR,
    RV_IOPMP_ERR_MSIADDRH,
    RV_IOPMP_MDCFG,
    RV_IOPMP_SRCMD_EN,
    RV_IOPMP_SRCMD_ENH,
    RV_IOPMP_ENTRY_ADDR,
    RV_IOPMP_ENTRY_ADDRH,
    RV_IOPMP_ENTRY_CFG,
    RV_IOPMP_ENTRY_USER_CFG
  } rv_iopmp_id_e;

  // Register width information to check illegal writes
  parameter logic [3:0] RV_IOPMP_PERMIT [20] = '{
    4'b 1111, // index[ 0] RV_IOPMP_VERSION
    4'b 1111, // index[ 1] RV_IOPMP_IMPLEMENTATION
    4'b 1111, // index[ 2] RV_IOPMP_HWCFG0
    4'b 1111, // index[ 3] RV_IOPMP_HWCFG1
    4'b 1111, // index[ 4] RV_IOPMP_HWCFG2
    4'b 1111, // index[ 5] RV_IOPMP_ENTRYOFFSET
    4'b 0111, // index[ 6] RV_IOPMP_ERR_CFG
    4'b 0011, // index[ 7] RV_IOPMP_ERR_INFO
    4'b 1111, // index[ 8] RV_IOPMP_ERR_REQADDR
    4'b 1111, // index[ 9] RV_IOPMP_ERR_REQADDRH
    4'b 1111, // index[10] RV_IOPMP_ERR_REQID
    4'b 1111, // index[11] RV_IOPMP_ERR_MSIADDR
    4'b 1111, // index[12] RV_IOPMP_ERR_MSIADDRH
    4'b 0011, // index[13] RV_IOPMP_MDCFG
    4'b 1111, // index[14] RV_IOPMP_SRCMD_EN
    4'b 1111, // index[15] RV_IOPMP_SRCMD_ENH
    4'b 1111, // index[16] RV_IOPMP_ENTRY_ADDR
    4'b 1111, // index[17] RV_IOPMP_ENTRY_ADDRH
    4'b 0011, // index[18] RV_IOPMP_ENTRY_CFG
    4'b 1111  // index[19] RV_IOPMP_ENTRY_USER_CFG
  };

endpackage

