// Copyright lowRISC contributors.
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0
//
// Register Top module auto-generated by `reggen`


`include "common_cells/assertions.svh"

module rv_iopmp_reg_top #(
  parameter type reg_req_t = logic,
  parameter type reg_rsp_t = logic,
  parameter int AW = 14,

  parameter int N_MDS     = 1,
  parameter int N_RRID    = 1,
  parameter int N_ENTRIES = 1,

  parameter type entry_t = logic
) (
  input logic clk_i,
  input logic rst_ni,
  input  reg_req_t reg_req_i,
  output reg_rsp_t reg_rsp_o,
  // To HW
  output rv_iopmp_reg_pkg::rv_iopmp_reg2hw_t reg2hw, // Write
  input  rv_iopmp_reg_pkg::rv_iopmp_hw2reg_t hw2reg, // Read

  output  logic[$clog2(N_ENTRIES) - 1: 0] entry_idx_o,
  output  entry_t                         entry_data_o,
  output  logic                           valid_o,

  // Config
  input devmode_i // If 1, explicit error return for unmapped register access
);

  import rv_iopmp_reg_pkg::* ;

  localparam int DW = 32;
  localparam int DBW = DW/8;                    // Byte Width

  localparam int ADDR_HIT_MDCFG_OFFSET = 13;
  localparam int ADDR_HIT_SRCMD_EN_OFFSET   = ADDR_HIT_MDCFG_OFFSET + N_MDS;
  localparam int ADDR_HIT_SRCMD_ENH_OFFSET  = ADDR_HIT_SRCMD_EN_OFFSET + N_RRID;
  localparam int ADDR_HIT_ENTRY_ADDR_OFFSET = ADDR_HIT_SRCMD_ENH_OFFSET + N_RRID;
  localparam int ADDR_HIT_ENTRY_ADDRH_OFFSET = ADDR_HIT_ENTRY_ADDR_OFFSET + N_ENTRIES;
  localparam int ADDR_HIT_ENTRY_CFG_OFFSET  = ADDR_HIT_ENTRY_ADDRH_OFFSET + N_ENTRIES;
  localparam int ADDR_HIT_ENTRY_USER_CFG_OFFSET = ADDR_HIT_ENTRY_CFG_OFFSET + N_ENTRIES;
  localparam int ADDR_HIT_SIZE              = ADDR_HIT_ENTRY_USER_CFG_OFFSET + N_ENTRIES;

  function automatic logic is_entry_addr_hit(int i);
      return  addr_hit[ADDR_HIT_ENTRY_ADDR_OFFSET + i] ||
              addr_hit[ADDR_HIT_ENTRY_ADDRH_OFFSET + i] ||
              addr_hit[ADDR_HIT_ENTRY_CFG_OFFSET + i];
  endfunction


  // register signals
  logic           reg_we;
  logic           reg_re;
  logic [BlockAw-1:0]  reg_addr;
  logic [DW-1:0]  reg_wdata;
  logic [DBW-1:0] reg_be;
  logic [DW-1:0]  reg_rdata;
  logic           reg_error;

  logic          addrmiss, wr_err;

  logic [DW-1:0] reg_rdata_next;

  // Below register interface can be changed
  reg_req_t  reg_intf_req;
  reg_rsp_t  reg_intf_rsp;


  assign reg_intf_req = reg_req_i;
  assign reg_rsp_o = reg_intf_rsp;


  assign reg_we = reg_intf_req.valid & reg_intf_req.write;
  assign reg_re = reg_intf_req.valid & ~reg_intf_req.write;
  assign reg_addr = reg_intf_req.addr[BlockAw-1:0];
  assign reg_wdata = reg_intf_req.wdata;
  assign reg_be = reg_intf_req.wstrb;
  assign reg_intf_rsp.rdata = reg_rdata;
  assign reg_intf_rsp.error = reg_error;
  assign reg_intf_rsp.ready = 1'b1;

  assign reg_rdata = reg_rdata_next ;
  assign reg_error = (devmode_i & addrmiss) | wr_err;


  // Define SW related signals
  // Format: <reg>_<field>_{wd|we|qs}
  //        or <reg>_{wd|we|qs} if field == 1 or 0
  logic [23:0] version_vendor_qs;
  logic [7:0] version_specver_qs;
  logic [31:0] implementation_qs;
  logic [1:0] hwcfg0_mdcfg_fmt_qs;
  logic [1:0] hwcfg0_srcmd_fmt_qs;
  logic hwcfg0_tor_en_qs;
  logic hwcfg0_sps_en_qs;
  logic hwcfg0_user_cfg_en_qs;
  logic hwcfg0_prient_prog_qs;
  logic hwcfg0_prient_prog_wd;
  logic hwcfg0_prient_prog_we;
  logic hwcfg0_rrid_transl_en_qs;
  logic hwcfg0_rrid_transl_prog_qs;
  logic hwcfg0_rrid_transl_prog_wd;
  logic hwcfg0_rrid_transl_prog_we;
  logic hwcfg0_chk_x_qs;
  logic hwcfg0_no_x_qs;
  logic hwcfg0_no_w_qs;
  logic hwcfg0_stall_en_qs;
  logic hwcfg0_peis_qs;
  logic hwcfg0_pees_qs;
  logic hwcfg0_mfr_en_qs;
  logic [6:0] hwcfg0_md_entry_num_qs;
  logic [6:0] hwcfg0_md_entry_num_wd;
  logic hwcfg0_md_entry_num_we;
  logic [5:0] hwcfg0_md_num_qs;
  logic hwcfg0_addrh_en_qs;
  logic hwcfg0_enable_qs;
  logic hwcfg0_enable_wd;
  logic hwcfg0_enable_we;
  logic [15:0] hwcfg1_rrid_num_qs;
  logic [15:0] hwcfg1_entry_num_qs;
  logic [15:0] hwcfg2_prio_entry_qs;
  logic [15:0] hwcfg2_prio_entry_wd;
  logic hwcfg2_prio_entry_we;
  logic [15:0] hwcfg2_rrid_transl_qs;
  logic [15:0] hwcfg2_rrid_transl_wd;
  logic hwcfg2_rrid_transl_we;
  logic [31:0] entryoffset_qs;
  logic err_cfg_lock_qs;
  logic err_cfg_lock_wd;
  logic err_cfg_lock_we;
  logic err_cfg_ie_qs;
  logic err_cfg_ie_wd;
  logic err_cfg_ie_we;
  logic err_cfg_rs_qs;
  logic err_cfg_rs_wd;
  logic err_cfg_rs_we;
  logic err_cfg_msi_en_qs;
  logic err_cfg_msi_en_wd;
  logic err_cfg_msi_en_we;
  logic err_cfg_stall_violation_en_qs;
  logic err_cfg_stall_violation_en_wd;
  logic err_cfg_stall_violation_en_we;
  logic [10:0] err_cfg_msidata_qs;
  logic [10:0] err_cfg_msidata_wd;
  logic err_cfg_msidata_we;
  logic err_info_v_qs;
  logic err_info_v_wd;
  logic err_info_v_we;
  logic [1:0] err_info_ttype_qs;
  logic err_info_msi_werr_qs;
  logic err_info_msi_werr_wd;
  logic err_info_msi_werr_we;
  logic [3:0] err_info_etype_qs;
  logic err_info_svc_qs;
  logic [31:0] err_reqaddr_qs;
  logic [31:0] err_reqaddrh_qs;
  logic [15:0] err_reqid_rrid_qs;
  logic [15:0] err_reqid_eid_qs;
  logic [31:0] err_msiaddr_qs;
  logic [31:0] err_msiaddrh_qs;

  logic [15:0] mdcfg_qs [N_MDS];
  logic [15:0] mdcfg_wd [N_MDS];
  logic [N_MDS - 1 : 0] mdcfg_we;

  logic [N_RRID - 1 : 0] srcmd_en_lock_qs;
  logic [N_RRID - 1 : 0] srcmd_en_lock_wd;
  logic [N_RRID - 1 : 0] srcmd_en_lock_we;
  logic [30:0] srcmd_en_md_qs [N_RRID];
  logic [30:0] srcmd_en_md_wd [N_RRID];
  logic [N_RRID - 1 : 0] srcmd_en_md_we;
  logic [31:0] srcmd_enh_qs [N_RRID];
  logic [31:0] srcmd_enh_wd [N_RRID];
  logic [N_RRID - 1 : 0] srcmd_enh_we;

  logic [31:0] entry_addr_qs [N_ENTRIES];
  logic [31:0] entry_addr_wd [N_ENTRIES];
  logic [N_ENTRIES - 1 : 0] entry_addr_we;
  logic [31:0] entry_addrh_qs [N_ENTRIES];
  logic [31:0] entry_addrh_wd [N_ENTRIES];
  logic [N_ENTRIES - 1 : 0] entry_addrh_we;
  logic [N_ENTRIES - 1 : 0] entry_cfg_r_qs;
  logic [N_ENTRIES - 1 : 0] entry_cfg_r_wd;
  logic [N_ENTRIES - 1 : 0] entry_cfg_r_we;
  logic [N_ENTRIES - 1 : 0] entry_cfg_w_qs;
  logic [N_ENTRIES - 1 : 0] entry_cfg_w_wd;
  logic [N_ENTRIES - 1 : 0] entry_cfg_w_we;
  logic [N_ENTRIES - 1 : 0] entry_cfg_x_qs;
  logic [N_ENTRIES - 1 : 0] entry_cfg_x_wd;
  logic [N_ENTRIES - 1 : 0] entry_cfg_x_we;
  logic [1:0] entry_cfg_a_qs [N_ENTRIES];
  logic [1:0] entry_cfg_a_wd [N_ENTRIES];
  logic [N_ENTRIES - 1 : 0] entry_cfg_a_we;
  logic [N_ENTRIES - 1 : 0] entry_cfg_sire_qs;
  logic [N_ENTRIES - 1 : 0] entry_cfg_sire_wd;
  logic [N_ENTRIES - 1 : 0] entry_cfg_sire_we;
  logic [N_ENTRIES - 1 : 0] entry_cfg_siwe_qs;
  logic [N_ENTRIES - 1 : 0] entry_cfg_siwe_wd;
  logic [N_ENTRIES - 1 : 0] entry_cfg_siwe_we;
  logic [N_ENTRIES - 1 : 0] entry_cfg_sixe_qs;
  logic [N_ENTRIES - 1 : 0] entry_cfg_sixe_wd;
  logic [N_ENTRIES - 1 : 0] entry_cfg_sixe_we;
  logic [N_ENTRIES - 1 : 0] entry_cfg_sere_qs;
  logic [N_ENTRIES - 1 : 0] entry_cfg_sere_wd;
  logic [N_ENTRIES - 1 : 0] entry_cfg_sere_we;
  logic [N_ENTRIES - 1 : 0] entry_cfg_sewe_qs;
  logic [N_ENTRIES - 1 : 0] entry_cfg_sewe_wd;
  logic [N_ENTRIES - 1 : 0] entry_cfg_sewe_we;
  logic [N_ENTRIES - 1 : 0] entry_cfg_sexe_qs;
  logic [N_ENTRIES - 1 : 0] entry_cfg_sexe_wd;
  logic [N_ENTRIES - 1 : 0] entry_cfg_sexe_we;
  logic [31:0] entry_user_cfg_qs [N_ENTRIES];
  logic [31:0] entry_user_cfg_wd [N_ENTRIES];
  logic [N_ENTRIES - 1 : 0] entry_user_cfg_we;

  // Register instances
  // R[version]: V(False)

  //   F[vendor]: 23:0
  prim_subreg #(
    .DW      (24),
    .SWACCESS("RO"),
    .RESVAL  (24'h0)
  ) u_version_vendor (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    .we     (1'b0),
    .wd     ('0  ),

    // from internal hardware
    .de     (1'b0),
    .d      ('0  ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.version.vendor.q ),

    // to register interface (read)
    .qs     (version_vendor_qs)
  );


  //   F[specver]: 31:24
  prim_subreg #(
    .DW      (8),
    .SWACCESS("RO"),
    .RESVAL  (8'h0)
  ) u_version_specver (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    .we     (1'b0),
    .wd     ('0  ),

    // from internal hardware
    .de     (1'b0),
    .d      ('0  ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.version.specver.q ),

    // to register interface (read)
    .qs     (version_specver_qs)
  );


  // R[implementation]: V(False)

  prim_subreg #(
    .DW      (32),
    .SWACCESS("RO"),
    .RESVAL  (32'h0)
  ) u_implementation (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    .we     (1'b0),
    .wd     ('0  ),

    // from internal hardware
    .de     (1'b0),
    .d      ('0  ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.implementation.q ),

    // to register interface (read)
    .qs     (implementation_qs)
  );


  // R[hwcfg0]: V(False)

  //   F[mdcfg_fmt]: 1:0
  prim_subreg #(
    .DW      (2),
    .SWACCESS("RO"),
    .RESVAL  (2'h0)
  ) u_hwcfg0_mdcfg_fmt (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    .we     (1'b0),
    .wd     ('0  ),

    // from internal hardware
    .de     (1'b0),
    .d      ('0  ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.hwcfg0.mdcfg_fmt.q ),

    // to register interface (read)
    .qs     (hwcfg0_mdcfg_fmt_qs)
  );


  //   F[srcmd_fmt]: 3:2
  prim_subreg #(
    .DW      (2),
    .SWACCESS("RO"),
    .RESVAL  (2'h0)
  ) u_hwcfg0_srcmd_fmt (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    .we     (1'b0),
    .wd     ('0  ),

    // from internal hardware
    .de     (1'b0),
    .d      ('0  ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.hwcfg0.srcmd_fmt.q ),

    // to register interface (read)
    .qs     (hwcfg0_srcmd_fmt_qs)
  );


  //   F[tor_en]: 4:4
  prim_subreg #(
    .DW      (1),
    .SWACCESS("RO"),
    .RESVAL  (1'h0)
  ) u_hwcfg0_tor_en (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    .we     (1'b0),
    .wd     ('0  ),

    // from internal hardware
    .de     (1'b0),
    .d      ('0  ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.hwcfg0.tor_en.q ),

    // to register interface (read)
    .qs     (hwcfg0_tor_en_qs)
  );


  //   F[sps_en]: 5:5
  prim_subreg #(
    .DW      (1),
    .SWACCESS("RO"),
    .RESVAL  (1'h0)
  ) u_hwcfg0_sps_en (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    .we     (1'b0),
    .wd     ('0  ),

    // from internal hardware
    .de     (1'b0),
    .d      ('0  ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.hwcfg0.sps_en.q ),

    // to register interface (read)
    .qs     (hwcfg0_sps_en_qs)
  );


  //   F[user_cfg_en]: 6:6
  prim_subreg #(
    .DW      (1),
    .SWACCESS("RO"),
    .RESVAL  (1'h0)
  ) u_hwcfg0_user_cfg_en (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    .we     (1'b0),
    .wd     ('0  ),

    // from internal hardware
    .de     (1'b0),
    .d      ('0  ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.hwcfg0.user_cfg_en.q ),

    // to register interface (read)
    .qs     (hwcfg0_user_cfg_en_qs)
  );


  //   F[prient_prog]: 7:7
  prim_subreg #(
    .DW      (1),
    .SWACCESS("W1C"),
    .RESVAL  (1'h0)
  ) u_hwcfg0_prient_prog (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    // from register interface
    .we     (hwcfg0_prient_prog_we),
    .wd     (hwcfg0_prient_prog_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0  ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.hwcfg0.prient_prog.q ),

    // to register interface (read)
    .qs     (hwcfg0_prient_prog_qs)
  );


  //   F[rrid_transl_en]: 8:8
  prim_subreg #(
    .DW      (1),
    .SWACCESS("RO"),
    .RESVAL  (1'h0)
  ) u_hwcfg0_rrid_transl_en (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    .we     (1'b0),
    .wd     ('0  ),

    // from internal hardware
    .de     (1'b0),
    .d      ('0  ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.hwcfg0.rrid_transl_en.q ),

    // to register interface (read)
    .qs     (hwcfg0_rrid_transl_en_qs)
  );


  //   F[rrid_transl_prog]: 9:9
  prim_subreg #(
    .DW      (1),
    .SWACCESS("W1C"),
    .RESVAL  (1'h0)
  ) u_hwcfg0_rrid_transl_prog (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    // from register interface
    .we     (hwcfg0_rrid_transl_prog_we),
    .wd     (hwcfg0_rrid_transl_prog_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0  ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.hwcfg0.rrid_transl_prog.q ),

    // to register interface (read)
    .qs     (hwcfg0_rrid_transl_prog_qs)
  );


  //   F[chk_x]: 10:10
  prim_subreg #(
    .DW      (1),
    .SWACCESS("RO"),
    .RESVAL  (1'h0)
  ) u_hwcfg0_chk_x (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    .we     (1'b0),
    .wd     ('0  ),

    // from internal hardware
    .de     (1'b0),
    .d      ('0  ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.hwcfg0.chk_x.q ),

    // to register interface (read)
    .qs     (hwcfg0_chk_x_qs)
  );


  //   F[no_x]: 11:11
  prim_subreg #(
    .DW      (1),
    .SWACCESS("RO"),
    .RESVAL  (1'h0)
  ) u_hwcfg0_no_x (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    .we     (1'b0),
    .wd     ('0  ),

    // from internal hardware
    .de     (1'b0),
    .d      ('0  ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.hwcfg0.no_x.q ),

    // to register interface (read)
    .qs     (hwcfg0_no_x_qs)
  );


  //   F[no_w]: 12:12
  prim_subreg #(
    .DW      (1),
    .SWACCESS("RO"),
    .RESVAL  (1'h0)
  ) u_hwcfg0_no_w (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    .we     (1'b0),
    .wd     ('0  ),

    // from internal hardware
    .de     (1'b0),
    .d      ('0  ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.hwcfg0.no_w.q ),

    // to register interface (read)
    .qs     (hwcfg0_no_w_qs)
  );


  //   F[stall_en]: 13:13
  prim_subreg #(
    .DW      (1),
    .SWACCESS("RO"),
    .RESVAL  (1'h0)
  ) u_hwcfg0_stall_en (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    .we     (1'b0),
    .wd     ('0  ),

    // from internal hardware
    .de     (1'b0),
    .d      ('0  ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.hwcfg0.stall_en.q ),

    // to register interface (read)
    .qs     (hwcfg0_stall_en_qs)
  );


  //   F[peis]: 14:14
  prim_subreg #(
    .DW      (1),
    .SWACCESS("RO"),
    .RESVAL  (1'h0)
  ) u_hwcfg0_peis (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    .we     (1'b0),
    .wd     ('0  ),

    // from internal hardware
    .de     (1'b0),
    .d      ('0  ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.hwcfg0.peis.q ),

    // to register interface (read)
    .qs     (hwcfg0_peis_qs)
  );


  //   F[pees]: 15:15
  prim_subreg #(
    .DW      (1),
    .SWACCESS("RO"),
    .RESVAL  (1'h0)
  ) u_hwcfg0_pees (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    .we     (1'b0),
    .wd     ('0  ),

    // from internal hardware
    .de     (1'b0),
    .d      ('0  ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.hwcfg0.pees.q ),

    // to register interface (read)
    .qs     (hwcfg0_pees_qs)
  );


  //   F[mfr_en]: 16:16
  prim_subreg #(
    .DW      (1),
    .SWACCESS("RO"),
    .RESVAL  (1'h0)
  ) u_hwcfg0_mfr_en (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    .we     (1'b0),
    .wd     ('0  ),

    // from internal hardware
    .de     (1'b0),
    .d      ('0  ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.hwcfg0.mfr_en.q ),

    // to register interface (read)
    .qs     (hwcfg0_mfr_en_qs)
  );


  //   F[md_entry_num]: 23:17
  prim_subreg #(
    .DW      (7),
    .SWACCESS("RW"),
    .RESVAL  (7'h0)
  ) u_hwcfg0_md_entry_num (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    // from register interface
    .we     (hwcfg0_md_entry_num_we),
    .wd     (hwcfg0_md_entry_num_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0  ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.hwcfg0.md_entry_num.q ),

    // to register interface (read)
    .qs     (hwcfg0_md_entry_num_qs)
  );


  //   F[md_num]: 29:24
  prim_subreg #(
    .DW      (6),
    .SWACCESS("RO"),
    .RESVAL  (6'h0)
  ) u_hwcfg0_md_num (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    .we     (1'b0),
    .wd     ('0  ),

    // from internal hardware
    .de     (1'b0),
    .d      ('0  ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.hwcfg0.md_num.q ),

    // to register interface (read)
    .qs     (hwcfg0_md_num_qs)
  );


  //   F[addrh_en]: 30:30
  prim_subreg #(
    .DW      (1),
    .SWACCESS("RO"),
    .RESVAL  (1'h0)
  ) u_hwcfg0_addrh_en (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    .we     (1'b0),
    .wd     ('0  ),

    // from internal hardware
    .de     (1'b0),
    .d      ('0  ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.hwcfg0.addrh_en.q ),

    // to register interface (read)
    .qs     (hwcfg0_addrh_en_qs)
  );


  //   F[enable]: 31:31
  prim_subreg #(
    .DW      (1),
    .SWACCESS("W1S"),
    .RESVAL  (1'h0)
  ) u_hwcfg0_enable (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    // from register interface
    .we     (hwcfg0_enable_we),
    .wd     (hwcfg0_enable_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0  ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.hwcfg0.enable.q ),

    // to register interface (read)
    .qs     (hwcfg0_enable_qs)
  );


  // R[hwcfg1]: V(False)

  //   F[rrid_num]: 15:0
  prim_subreg #(
    .DW      (16),
    .SWACCESS("RO"),
    .RESVAL  (16'h0)
  ) u_hwcfg1_rrid_num (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    .we     (1'b0),
    .wd     ('0  ),

    // from internal hardware
    .de     (1'b0),
    .d      ('0  ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.hwcfg1.rrid_num.q ),

    // to register interface (read)
    .qs     (hwcfg1_rrid_num_qs)
  );


  //   F[entry_num]: 31:16
  prim_subreg #(
    .DW      (16),
    .SWACCESS("RO"),
    .RESVAL  (16'h0)
  ) u_hwcfg1_entry_num (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    .we     (1'b0),
    .wd     ('0  ),

    // from internal hardware
    .de     (1'b0),
    .d      ('0  ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.hwcfg1.entry_num.q ),

    // to register interface (read)
    .qs     (hwcfg1_entry_num_qs)
  );


  // R[hwcfg2]: V(False)

  //   F[prio_entry]: 15:0
  prim_subreg #(
    .DW      (16),
    .SWACCESS("RW"),
    .RESVAL  (16'h0)
  ) u_hwcfg2_prio_entry (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    // from register interface
    .we     (hwcfg2_prio_entry_we),
    .wd     (hwcfg2_prio_entry_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0  ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.hwcfg2.prio_entry.q ),

    // to register interface (read)
    .qs     (hwcfg2_prio_entry_qs)
  );


  //   F[rrid_transl]: 31:16
  prim_subreg #(
    .DW      (16),
    .SWACCESS("RW"),
    .RESVAL  (16'h0)
  ) u_hwcfg2_rrid_transl (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    // from register interface
    .we     (hwcfg2_rrid_transl_we),
    .wd     (hwcfg2_rrid_transl_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0  ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.hwcfg2.rrid_transl.q ),

    // to register interface (read)
    .qs     (hwcfg2_rrid_transl_qs)
  );


  // R[entryoffset]: V(False)

  prim_subreg #(
    .DW      (32),
    .SWACCESS("RO"),
    .RESVAL  (32'h0)
  ) u_entryoffset (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    .we     (1'b0),
    .wd     ('0  ),

    // from internal hardware
    .de     (1'b0),
    .d      ('0  ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.entryoffset.q ),

    // to register interface (read)
    .qs     (entryoffset_qs)
  );


  // R[err_cfg]: V(False)

  //   F[lock]: 0:0
  prim_subreg #(
    .DW      (1),
    .SWACCESS("W1S"),
    .RESVAL  (1'h0)
  ) u_err_cfg_lock (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    // from register interface
    .we     (err_cfg_lock_we),
    .wd     (err_cfg_lock_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0  ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.err_cfg.lock.q ),

    // to register interface (read)
    .qs     (err_cfg_lock_qs)
  );


  //   F[ie]: 1:1
  prim_subreg #(
    .DW      (1),
    .SWACCESS("RW"),
    .RESVAL  (1'h0)
  ) u_err_cfg_ie (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    // from register interface
    .we     (err_cfg_ie_we),
    .wd     (err_cfg_ie_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0  ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.err_cfg.ie.q ),

    // to register interface (read)
    .qs     (err_cfg_ie_qs)
  );


  //   F[rs]: 2:2
  prim_subreg #(
    .DW      (1),
    .SWACCESS("RW"),
    .RESVAL  (1'h0)
  ) u_err_cfg_rs (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    // from register interface
    .we     (err_cfg_rs_we),
    .wd     (err_cfg_rs_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0  ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.err_cfg.rs.q ),

    // to register interface (read)
    .qs     (err_cfg_rs_qs)
  );


  //   F[msi_en]: 3:3
  prim_subreg #(
    .DW      (1),
    .SWACCESS("RW"),
    .RESVAL  (1'h0)
  ) u_err_cfg_msi_en (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    // from register interface
    .we     (err_cfg_msi_en_we),
    .wd     (err_cfg_msi_en_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0  ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.err_cfg.msi_en.q ),

    // to register interface (read)
    .qs     (err_cfg_msi_en_qs)
  );


  //   F[stall_violation_en]: 4:4
  prim_subreg #(
    .DW      (1),
    .SWACCESS("RW"),
    .RESVAL  (1'h0)
  ) u_err_cfg_stall_violation_en (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    // from register interface
    .we     (err_cfg_stall_violation_en_we),
    .wd     (err_cfg_stall_violation_en_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0  ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.err_cfg.stall_violation_en.q ),

    // to register interface (read)
    .qs     (err_cfg_stall_violation_en_qs)
  );


  //   F[msidata]: 18:8
  prim_subreg #(
    .DW      (11),
    .SWACCESS("RW"),
    .RESVAL  (11'h0)
  ) u_err_cfg_msidata (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    // from register interface
    .we     (err_cfg_msidata_we),
    .wd     (err_cfg_msidata_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0  ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.err_cfg.msidata.q ),

    // to register interface (read)
    .qs     (err_cfg_msidata_qs)
  );


  // R[err_info]: V(False)

  //   F[v]: 0:0
  prim_subreg #(
    .DW      (1),
    .SWACCESS("W1C"),
    .RESVAL  (1'h0)
  ) u_err_info_v (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    // from register interface
    .we     (err_info_v_we),
    .wd     (err_info_v_wd),

    // from internal hardware
    .de     (hw2reg.err_info.v.de),
    .d      (hw2reg.err_info.v.d ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.err_info.v.q ),

    // to register interface (read)
    .qs     (err_info_v_qs)
  );


  //   F[ttype]: 2:1
  prim_subreg #(
    .DW      (2),
    .SWACCESS("RO"),
    .RESVAL  (2'h0)
  ) u_err_info_ttype (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    .we     (1'b0),
    .wd     ('0  ),

    // from internal hardware
    .de     (hw2reg.err_info.ttype.de),
    .d      (hw2reg.err_info.ttype.d ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.err_info.ttype.q ),

    // to register interface (read)
    .qs     (err_info_ttype_qs)
  );


  //   F[msi_werr]: 3:3
  prim_subreg #(
    .DW      (1),
    .SWACCESS("W1C"),
    .RESVAL  (1'h0)
  ) u_err_info_msi_werr (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    // from register interface
    .we     (err_info_msi_werr_we),
    .wd     (err_info_msi_werr_wd),

    // from internal hardware
    .de     (hw2reg.err_info.msi_werr.de),
    .d      (hw2reg.err_info.msi_werr.d ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.err_info.msi_werr.q ),

    // to register interface (read)
    .qs     (err_info_msi_werr_qs)
  );


  //   F[etype]: 7:4
  prim_subreg #(
    .DW      (4),
    .SWACCESS("RO"),
    .RESVAL  (4'h0)
  ) u_err_info_etype (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    .we     (1'b0),
    .wd     ('0  ),

    // from internal hardware
    .de     (hw2reg.err_info.etype.de),
    .d      (hw2reg.err_info.etype.d ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.err_info.etype.q ),

    // to register interface (read)
    .qs     (err_info_etype_qs)
  );


  //   F[svc]: 8:8
  prim_subreg #(
    .DW      (1),
    .SWACCESS("RO"),
    .RESVAL  (1'h0)
  ) u_err_info_svc (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    .we     (1'b0),
    .wd     ('0  ),

    // from internal hardware
    .de     (hw2reg.err_info.svc.de),
    .d      (hw2reg.err_info.svc.d ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.err_info.svc.q ),

    // to register interface (read)
    .qs     (err_info_svc_qs)
  );


  // R[err_reqaddr]: V(False)

  prim_subreg #(
    .DW      (32),
    .SWACCESS("RO"),
    .RESVAL  (32'h0)
  ) u_err_reqaddr (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    .we     (1'b0),
    .wd     ('0  ),

    // from internal hardware
    .de     (hw2reg.err_reqaddr.de),
    .d      (hw2reg.err_reqaddr.d ),

    // to internal hardware
    .qe     (),
    .q      (),

    // to register interface (read)
    .qs     (err_reqaddr_qs)
  );


  // R[err_reqaddrh]: V(False)

  prim_subreg #(
    .DW      (32),
    .SWACCESS("RO"),
    .RESVAL  (32'h0)
  ) u_err_reqaddrh (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    .we     (1'b0),
    .wd     ('0  ),

    // from internal hardware
    .de     (hw2reg.err_reqaddrh.de),
    .d      (hw2reg.err_reqaddrh.d ),

    // to internal hardware
    .qe     (),
    .q      (),

    // to register interface (read)
    .qs     (err_reqaddrh_qs)
  );


  // R[err_reqid]: V(False)

  //   F[rrid]: 15:0
  prim_subreg #(
    .DW      (16),
    .SWACCESS("RO"),
    .RESVAL  (16'h0)
  ) u_err_reqid_rrid (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    .we     (1'b0),
    .wd     ('0  ),

    // from internal hardware
    .de     (hw2reg.err_reqid.rrid.de),
    .d      (hw2reg.err_reqid.rrid.d ),

    // to internal hardware
    .qe     (),
    .q      (),

    // to register interface (read)
    .qs     (err_reqid_rrid_qs)
  );


  //   F[eid]: 31:16
  prim_subreg #(
    .DW      (16),
    .SWACCESS("RO"),
    .RESVAL  (16'h0)
  ) u_err_reqid_eid (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    .we     (1'b0),
    .wd     ('0  ),

    // from internal hardware
    .de     (hw2reg.err_reqid.eid.de),
    .d      (hw2reg.err_reqid.eid.d ),

    // to internal hardware
    .qe     (),
    .q      (),

    // to register interface (read)
    .qs     (err_reqid_eid_qs)
  );


  // R[err_msiaddr]: V(False)

  prim_subreg #(
    .DW      (32),
    .SWACCESS("RO"),
    .RESVAL  (32'h0)
  ) u_err_msiaddr (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    .we     (1'b0),
    .wd     ('0  ),

    // from internal hardware
    .de     (hw2reg.err_msiaddr.de),
    .d      (hw2reg.err_msiaddr.d ),

    // to internal hardware
    .qe     (),
    .q      (),

    // to register interface (read)
    .qs     (err_msiaddr_qs)
  );


  // R[err_msiaddrh]: V(False)

  prim_subreg #(
    .DW      (32),
    .SWACCESS("RO"),
    .RESVAL  (32'h0)
  ) u_err_msiaddrh (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    .we     (1'b0),
    .wd     ('0  ),

    // from internal hardware
    .de     (hw2reg.err_msiaddrh.de),
    .d      (hw2reg.err_msiaddrh.d ),

    // to internal hardware
    .qe     (),
    .q      (),

    // to register interface (read)
    .qs     (err_msiaddrh_qs)
  );


  // R[mdcfg]: V(False)
  for(genvar i = 0; i < N_MDS; i++) begin : gen_mdcfg_reg
    prim_subreg #(
      .DW      (16),
      .SWACCESS("RW"),
      .RESVAL  (16'h0)
    ) u_mdcfg (
      .clk_i   (clk_i    ),
      .rst_ni  (rst_ni  ),

      // from register interface
      .we     (mdcfg_we[i]),
      .wd     (mdcfg_wd[i]),

      // from internal hardware
      .de     (1'b0),
      .d      ('0  ),

      // to internal hardware
      .qe     (),
      .q      (reg2hw.mdcfg[i].q ),

      // to register interface (read)
      .qs     (mdcfg_qs[i])
    );

  end // gen_mdcfg_reg

  // R[srcmd_en]: V(False)
  for(genvar i = 0; i < N_RRID; i++) begin : gen_srcmd_reg
    //   F[lock]: 0:0
    prim_subreg #(
      .DW      (1),
      .SWACCESS("W1S"),
      .RESVAL  (1'h0)
    ) u_srcmd_en_lock (
      .clk_i   (clk_i    ),
      .rst_ni  (rst_ni  ),

      // from register interface
      .we     (srcmd_en_lock_we[i]),
      .wd     (srcmd_en_lock_wd[i]),

      // from internal hardware
      .de     (1'b0),
      .d      ('0  ),

      // to internal hardware
      .qe     (),
      .q      (reg2hw.srcmd_en[i].lock.q ),

      // to register interface (read)
      .qs     (srcmd_en_lock_qs[i])
    );


    //   F[md]: 31:1
    prim_subreg #(
      .DW      (31),
      .SWACCESS("RW"),
      .RESVAL  (31'h0)
    ) u_srcmd_en_md (
      .clk_i   (clk_i    ),
      .rst_ni  (rst_ni  ),

      // from register interface
      .we     (srcmd_en_md_we[i]),
      .wd     (srcmd_en_md_wd[i]),

      // from internal hardware
      .de     (1'b0),
      .d      ('0  ),

      // to internal hardware
      .qe     (),
      .q      (reg2hw.srcmd_en[i].md.q ),

      // to register interface (read)
      .qs     (srcmd_en_md_qs[i])
    );


    // R[srcmd_enh]: V(False)

    prim_subreg #(
      .DW      (32),
      .SWACCESS("RW"),
      .RESVAL  (32'h0)
    ) u_srcmd_enh (
      .clk_i   (clk_i    ),
      .rst_ni  (rst_ni  ),

      // from register interface
      .we     (srcmd_enh_we[i]),
      .wd     (srcmd_enh_wd[i]),

      // from internal hardware
      .de     (1'b0),
      .d      ('0  ),

      // to internal hardware
      .qe     (),
      .q      (reg2hw.srcmd_enh[i].q ),

      // to register interface (read)
      .qs     (srcmd_enh_qs[i])
    );
  end // gen_srcmd_reg

  for(genvar i = 0; i < N_ENTRIES; i++) begin : gen_entries_reg

    // R[entry_addr]: V(False)
    prim_subreg #(
      .DW      (32),
      .SWACCESS("RW"),
      .RESVAL  (32'h0)
    ) u_entry_addr (
      .clk_i   (clk_i    ),
      .rst_ni  (rst_ni  ),

      // from register interface
      .we     (entry_addr_we[i]),
      .wd     (entry_addr_wd[i]),

      // from internal hardware
      .de     (1'b0),
      .d      ('0  ),

      // to internal hardware
      .qe     (),
      .q      (reg2hw.entry_addr[i].q ),

      // to register interface (read)
      .qs     (entry_addr_qs[i])
    );


    // R[entry_addrh]: V(False)

    prim_subreg #(
      .DW      (32),
      .SWACCESS("RW"),
      .RESVAL  (32'h0)
    ) u_entry_addrh (
      .clk_i   (clk_i    ),
      .rst_ni  (rst_ni  ),

      // from register interface
      .we     (entry_addrh_we[i]),
      .wd     (entry_addrh_wd[i]),

      // from internal hardware
      .de     (1'b0),
      .d      ('0  ),

      // to internal hardware
      .qe     (),
      .q      (reg2hw.entry_addrh[i].q ),

      // to register interface (read)
      .qs     (entry_addrh_qs[i])
    );


    // R[entry_cfg]: V(False)

    //   F[r]: 0:0
    prim_subreg #(
      .DW      (1),
      .SWACCESS("RW"),
      .RESVAL  (1'h0)
    ) u_entry_cfg_r (
      .clk_i   (clk_i    ),
      .rst_ni  (rst_ni  ),

      // from register interface
      .we     (entry_cfg_r_we[i]),
      .wd     (entry_cfg_r_wd[i]),

      // from internal hardware
      .de     (1'b0),
      .d      ('0  ),

      // to internal hardware
      .qe     (),
      .q      (reg2hw.entry_cfg[i].r.q ),

      // to register interface (read)
      .qs     (entry_cfg_r_qs[i])
    );


    //   F[w]: 1:1
    prim_subreg #(
      .DW      (1),
      .SWACCESS("RW"),
      .RESVAL  (1'h0)
    ) u_entry_cfg_w (
      .clk_i   (clk_i    ),
      .rst_ni  (rst_ni  ),

      // from register interface
      .we     (entry_cfg_w_we[i]),
      .wd     (entry_cfg_w_wd[i]),

      // from internal hardware
      .de     (1'b0),
      .d      ('0  ),

      // to internal hardware
      .qe     (),
      .q      (reg2hw.entry_cfg[i].w.q ),

      // to register interface (read)
      .qs     (entry_cfg_w_qs[i])
    );


    //   F[x]: 2:2
    prim_subreg #(
      .DW      (1),
      .SWACCESS("RW"),
      .RESVAL  (1'h0)
    ) u_entry_cfg_x (
      .clk_i   (clk_i    ),
      .rst_ni  (rst_ni  ),

      // from register interface
      .we     (entry_cfg_x_we[i]),
      .wd     (entry_cfg_x_wd[i]),

      // from internal hardware
      .de     (1'b0),
      .d      ('0  ),

      // to internal hardware
      .qe     (),
      .q      (reg2hw.entry_cfg[i].x.q ),

      // to register interface (read)
      .qs     (entry_cfg_x_qs[i])
    );


    //   F[a]: 4:3
    prim_subreg #(
      .DW      (2),
      .SWACCESS("RW"),
      .RESVAL  (2'h0)
    ) u_entry_cfg_a (
      .clk_i   (clk_i    ),
      .rst_ni  (rst_ni  ),

      // from register interface
      .we     (entry_cfg_a_we[i]),
      .wd     (entry_cfg_a_wd[i]),

      // from internal hardware
      .de     (1'b0),
      .d      ('0  ),

      // to internal hardware
      .qe     (),
      .q      (reg2hw.entry_cfg[i].a.q ),

      // to register interface (read)
      .qs     (entry_cfg_a_qs[i])
    );


    //   F[sire]: 5:5
    prim_subreg #(
      .DW      (1),
      .SWACCESS("RW"),
      .RESVAL  (1'h0)
    ) u_entry_cfg_sire (
      .clk_i   (clk_i    ),
      .rst_ni  (rst_ni  ),

      // from register interface
      .we     (entry_cfg_sire_we[i]),
      .wd     (entry_cfg_sire_wd[i]),

      // from internal hardware
      .de     (1'b0),
      .d      ('0  ),

      // to internal hardware
      .qe     (),
      .q      (reg2hw.entry_cfg[i].sire.q ),

      // to register interface (read)
      .qs     (entry_cfg_sire_qs[i])
    );


    //   F[siwe]: 6:6
    prim_subreg #(
      .DW      (1),
      .SWACCESS("RW"),
      .RESVAL  (1'h0)
    ) u_entry_cfg_siwe (
      .clk_i   (clk_i    ),
      .rst_ni  (rst_ni  ),

      // from register interface
      .we     (entry_cfg_siwe_we[i]),
      .wd     (entry_cfg_siwe_wd[i]),

      // from internal hardware
      .de     (1'b0),
      .d      ('0  ),

      // to internal hardware
      .qe     (),
      .q      (reg2hw.entry_cfg[i].siwe.q ),

      // to register interface (read)
      .qs     (entry_cfg_siwe_qs[i])
    );


    //   F[sixe]: 7:7
    prim_subreg #(
      .DW      (1),
      .SWACCESS("RW"),
      .RESVAL  (1'h0)
    ) u_entry_cfg_sixe (
      .clk_i   (clk_i    ),
      .rst_ni  (rst_ni  ),

      // from register interface
      .we     (entry_cfg_sixe_we[i]),
      .wd     (entry_cfg_sixe_wd[i]),

      // from internal hardware
      .de     (1'b0),
      .d      ('0  ),

      // to internal hardware
      .qe     (),
      .q      (reg2hw.entry_cfg[i].sixe.q ),

      // to register interface (read)
      .qs     (entry_cfg_sixe_qs[i])
    );


    //   F[sere]: 8:8
    prim_subreg #(
      .DW      (1),
      .SWACCESS("RW"),
      .RESVAL  (1'h0)
    ) u_entry_cfg_sere (
      .clk_i   (clk_i    ),
      .rst_ni  (rst_ni  ),

      // from register interface
      .we     (entry_cfg_sere_we[i]),
      .wd     (entry_cfg_sere_wd[i]),

      // from internal hardware
      .de     (1'b0),
      .d      ('0  ),

      // to internal hardware
      .qe     (),
      .q      (reg2hw.entry_cfg[i].sere.q ),

      // to register interface (read)
      .qs     (entry_cfg_sere_qs[i])
    );


    //   F[sewe]: 9:9
    prim_subreg #(
      .DW      (1),
      .SWACCESS("RW"),
      .RESVAL  (1'h0)
    ) u_entry_cfg_sewe (
      .clk_i   (clk_i    ),
      .rst_ni  (rst_ni  ),

      // from register interface
      .we     (entry_cfg_sewe_we[i]),
      .wd     (entry_cfg_sewe_wd[i]),

      // from internal hardware
      .de     (1'b0),
      .d      ('0  ),

      // to internal hardware
      .qe     (),
      .q      (reg2hw.entry_cfg[i].sewe.q ),

      // to register interface (read)
      .qs     (entry_cfg_sewe_qs[i])
    );


    //   F[sexe]: 10:10
    prim_subreg #(
      .DW      (1),
      .SWACCESS("RW"),
      .RESVAL  (1'h0)
    ) u_entry_cfg_sexe (
      .clk_i   (clk_i    ),
      .rst_ni  (rst_ni  ),

      // from register interface
      .we     (entry_cfg_sexe_we[i]),
      .wd     (entry_cfg_sexe_wd[i]),

      // from internal hardware
      .de     (1'b0),
      .d      ('0  ),

      // to internal hardware
      .qe     (),
      .q      (reg2hw.entry_cfg[i].sexe.q ),

      // to register interface (read)
      .qs     (entry_cfg_sexe_qs[i])
    );


    // R[entry_user_cfg]: V(False)

    prim_subreg #(
      .DW      (32),
      .SWACCESS("RW"),
      .RESVAL  (32'h0)
    ) u_entry_user_cfg (
      .clk_i   (clk_i    ),
      .rst_ni  (rst_ni  ),

      // from register interface
      .we     (entry_user_cfg_we[i]),
      .wd     (entry_user_cfg_wd[i]),

      // from internal hardware
      .de     (1'b0),
      .d      ('0  ),

      // to internal hardware
      .qe     (),
      .q      (reg2hw.entry_user_cfg[i].q ),

      // to register interface (read)
      .qs     (entry_user_cfg_qs[i])
    );

  end // gen_entries_reg


  logic [ADDR_HIT_SIZE - 1:0] addr_hit;
  always_comb begin
    addr_hit = '0;
    addr_hit[ 0] = (reg_addr == RV_IOPMP_VERSION_OFFSET);
    addr_hit[ 1] = (reg_addr == RV_IOPMP_IMPLEMENTATION_OFFSET);
    addr_hit[ 2] = (reg_addr == RV_IOPMP_HWCFG0_OFFSET);
    addr_hit[ 3] = (reg_addr == RV_IOPMP_HWCFG1_OFFSET);
    addr_hit[ 4] = (reg_addr == RV_IOPMP_HWCFG2_OFFSET);
    addr_hit[ 5] = (reg_addr == RV_IOPMP_ENTRYOFFSET_OFFSET);
    addr_hit[ 6] = (reg_addr == RV_IOPMP_ERR_CFG_OFFSET);
    addr_hit[ 7] = (reg_addr == RV_IOPMP_ERR_INFO_OFFSET);
    addr_hit[ 8] = (reg_addr == RV_IOPMP_ERR_REQADDR_OFFSET);
    addr_hit[ 9] = (reg_addr == RV_IOPMP_ERR_REQADDRH_OFFSET);
    addr_hit[10] = (reg_addr == RV_IOPMP_ERR_REQID_OFFSET);
    addr_hit[11] = (reg_addr == RV_IOPMP_ERR_MSIADDR_OFFSET);
    addr_hit[12] = (reg_addr == RV_IOPMP_ERR_MSIADDRH_OFFSET);

    for (int i = 0; i < N_MDS; i++) begin
      addr_hit[13 + i] = (reg_addr == (RV_IOPMP_MDCFG_OFFSET + i * 4));
    end
    for (int i = 0; i < N_RRID; i++) begin
      addr_hit[ADDR_HIT_SRCMD_EN_OFFSET + i] = (reg_addr == (RV_IOPMP_SRCMD_EN_OFFSET + i * 32));
      addr_hit[ADDR_HIT_SRCMD_ENH_OFFSET + i] = (reg_addr == (RV_IOPMP_SRCMD_ENH_OFFSET + i * 32));
    end
    for (int i = 0; i < N_ENTRIES; i++) begin
      addr_hit[ADDR_HIT_ENTRY_ADDR_OFFSET + i] = (reg_addr == (RV_IOPMP_ENTRY_ADDR_OFFSET + i * 16));
      addr_hit[ADDR_HIT_ENTRY_ADDRH_OFFSET + i] = (reg_addr == (RV_IOPMP_ENTRY_ADDRH_OFFSET + i * 16));
      addr_hit[ADDR_HIT_ENTRY_CFG_OFFSET + i] = (reg_addr == (RV_IOPMP_ENTRY_CFG_OFFSET + i * 16));
      addr_hit[ADDR_HIT_ENTRY_USER_CFG_OFFSET + i] = (reg_addr == (RV_IOPMP_ENTRY_USER_CFG_OFFSET + i * 16));
    end
  end

  assign addrmiss = (reg_re || reg_we) ? ~|addr_hit : 1'b0 ;

  logic err_mdcfg, err_srcmd_en, err_srcmd_enh, err_entry_addr, err_entry_addrh, err_entry_cfg, err_entry_user_cfg;

  // Check sub-word write is permitted
  always_comb begin
    wr_err = (reg_we &
              ((addr_hit[ 0] & (|(RV_IOPMP_PERMIT[ 0] & ~reg_be))) |
               (addr_hit[ 1] & (|(RV_IOPMP_PERMIT[ 1] & ~reg_be))) |
               (addr_hit[ 2] & (|(RV_IOPMP_PERMIT[ 2] & ~reg_be))) |
               (addr_hit[ 3] & (|(RV_IOPMP_PERMIT[ 3] & ~reg_be))) |
               (addr_hit[ 4] & (|(RV_IOPMP_PERMIT[ 4] & ~reg_be))) |
               (addr_hit[ 5] & (|(RV_IOPMP_PERMIT[ 5] & ~reg_be))) |
               (addr_hit[ 6] & (|(RV_IOPMP_PERMIT[ 6] & ~reg_be))) |
               (addr_hit[ 7] & (|(RV_IOPMP_PERMIT[ 7] & ~reg_be))) |
               (addr_hit[ 8] & (|(RV_IOPMP_PERMIT[ 8] & ~reg_be))) |
               (addr_hit[ 9] & (|(RV_IOPMP_PERMIT[ 9] & ~reg_be))) |
               (addr_hit[10] & (|(RV_IOPMP_PERMIT[10] & ~reg_be))) |
               (addr_hit[11] & (|(RV_IOPMP_PERMIT[11] & ~reg_be))) |
               (addr_hit[12] & (|(RV_IOPMP_PERMIT[12] & ~reg_be))) |
               (addr_hit[13] & (|(RV_IOPMP_PERMIT[13] & ~reg_be))) |
               (addr_hit[14] & (|(RV_IOPMP_PERMIT[14] & ~reg_be))) |
               (addr_hit[15] & (|(RV_IOPMP_PERMIT[15] & ~reg_be))) |
               (addr_hit[16] & (|(RV_IOPMP_PERMIT[16] & ~reg_be))) |
               (addr_hit[17] & (|(RV_IOPMP_PERMIT[17] & ~reg_be))) |
               (addr_hit[18] & (|(RV_IOPMP_PERMIT[18] & ~reg_be))) |
               (addr_hit[19] & (|(RV_IOPMP_PERMIT[19] & ~reg_be))) |
               err_mdcfg | err_srcmd_en | err_srcmd_enh | err_entry_addr
               | err_entry_addrh | err_entry_cfg | err_entry_user_cfg));
  end

  assign err_mdcfg = (|addr_hit[13 + N_MDS -1 : 13]  & (|(RV_IOPMP_PERMIT[13] & ~reg_be)));
  assign err_srcmd_en = (|addr_hit[ADDR_HIT_SRCMD_EN_OFFSET + N_RRID -1 : ADDR_HIT_SRCMD_EN_OFFSET]
                        & (|(RV_IOPMP_PERMIT[14] & ~reg_be)));
  assign err_srcmd_enh = (|addr_hit[ADDR_HIT_SRCMD_ENH_OFFSET + N_RRID -1 : ADDR_HIT_SRCMD_ENH_OFFSET]
                        & (|(RV_IOPMP_PERMIT[15] & ~reg_be)));
  assign err_entry_addr = (|addr_hit[ADDR_HIT_ENTRY_ADDR_OFFSET + N_ENTRIES -1 : ADDR_HIT_ENTRY_ADDR_OFFSET]
                        & (|(RV_IOPMP_PERMIT[16] & ~reg_be)));
  assign err_entry_addrh = (|addr_hit[ADDR_HIT_ENTRY_ADDRH_OFFSET + N_ENTRIES -1 : ADDR_HIT_ENTRY_ADDRH_OFFSET]
                        & (|(RV_IOPMP_PERMIT[17] & ~reg_be)));
  assign err_entry_cfg = (|addr_hit[ADDR_HIT_ENTRY_CFG_OFFSET + N_ENTRIES -1 : ADDR_HIT_ENTRY_CFG_OFFSET]
                        & (|(RV_IOPMP_PERMIT[18] & ~reg_be)));
  assign err_entry_user_cfg = (|addr_hit[ADDR_HIT_ENTRY_USER_CFG_OFFSET + N_ENTRIES -1 : ADDR_HIT_ENTRY_USER_CFG_OFFSET]
                        & (|(RV_IOPMP_PERMIT[19] & ~reg_be)));

  assign hwcfg0_prient_prog_we = addr_hit[2] & reg_we & !reg_error;
  assign hwcfg0_prient_prog_wd = reg_wdata[7];

  assign hwcfg0_rrid_transl_prog_we = addr_hit[2] & reg_we & !reg_error;
  assign hwcfg0_rrid_transl_prog_wd = reg_wdata[9];

  assign hwcfg0_md_entry_num_we = addr_hit[2] & reg_we & !reg_error;
  assign hwcfg0_md_entry_num_wd = reg_wdata[23:17];

  assign hwcfg0_enable_we = addr_hit[2] & reg_we & !reg_error;
  assign hwcfg0_enable_wd = reg_wdata[31];

  assign hwcfg2_prio_entry_we = addr_hit[4] & reg_we & !reg_error;
  assign hwcfg2_prio_entry_wd = reg_wdata[15:0];

  assign hwcfg2_rrid_transl_we = addr_hit[4] & reg_we & !reg_error;
  assign hwcfg2_rrid_transl_wd = reg_wdata[31:16];

  assign err_cfg_lock_we = addr_hit[6] & reg_we & !reg_error;
  assign err_cfg_lock_wd = reg_wdata[0];

  assign err_cfg_ie_we = addr_hit[6] & reg_we & !reg_error;
  assign err_cfg_ie_wd = reg_wdata[1];

  assign err_cfg_rs_we = addr_hit[6] & reg_we & !reg_error;
  assign err_cfg_rs_wd = reg_wdata[2];

  assign err_cfg_msi_en_we = addr_hit[6] & reg_we & !reg_error;
  assign err_cfg_msi_en_wd = reg_wdata[3];

  assign err_cfg_stall_violation_en_we = addr_hit[6] & reg_we & !reg_error;
  assign err_cfg_stall_violation_en_wd = reg_wdata[4];

  assign err_cfg_msidata_we = addr_hit[6] & reg_we & !reg_error;
  assign err_cfg_msidata_wd = reg_wdata[18:8];

  assign err_info_v_we = addr_hit[7] & reg_we & !reg_error;
  assign err_info_v_wd = reg_wdata[0];

  assign err_info_msi_werr_we = addr_hit[7] & reg_we & !reg_error;
  assign err_info_msi_werr_wd = reg_wdata[3];

  for (genvar i = 0; i < N_MDS; i++) begin : gen_mdcfg_reg_we
    assign mdcfg_we[i] = addr_hit[13 + i] & reg_we & !reg_error;
    assign mdcfg_wd[i] = reg_wdata[15:0];
  end

  for (genvar i = 0; i < N_RRID; i++) begin : gen_srcmd_reg_we
    assign srcmd_en_lock_we[i] = addr_hit[ADDR_HIT_SRCMD_EN_OFFSET + i] & reg_we & !reg_error;
    assign srcmd_en_lock_wd[i] = reg_wdata[0];

    assign srcmd_en_md_we[i] = addr_hit[ADDR_HIT_SRCMD_EN_OFFSET + i] & reg_we & !reg_error;
    assign srcmd_en_md_wd[i] = reg_wdata[31:1];

    assign srcmd_enh_we[i] = addr_hit[ADDR_HIT_SRCMD_ENH_OFFSET + i] & reg_we & !reg_error;
    assign srcmd_enh_wd[i] = reg_wdata[31:0];
  end

  for (genvar i = 0; i < N_ENTRIES; i++) begin : gen_entries_reg_we
    assign entry_addr_we[i] = addr_hit[ADDR_HIT_ENTRY_ADDR_OFFSET + i] & reg_we & !reg_error;
    assign entry_addr_wd[i] = reg_wdata[31:0];

    assign entry_addrh_we[i] = addr_hit[ADDR_HIT_ENTRY_ADDRH_OFFSET + i] & reg_we & !reg_error;
    assign entry_addrh_wd[i] = reg_wdata[31:0];

    assign entry_cfg_r_we[i] = addr_hit[ADDR_HIT_ENTRY_CFG_OFFSET + i] & reg_we & !reg_error;
    assign entry_cfg_r_wd[i] = reg_wdata[0];

    assign entry_cfg_w_we[i] = addr_hit[ADDR_HIT_ENTRY_CFG_OFFSET + i] & reg_we & !reg_error;
    assign entry_cfg_w_wd[i] = reg_wdata[1];

    assign entry_cfg_x_we[i] = addr_hit[ADDR_HIT_ENTRY_CFG_OFFSET + i] & reg_we & !reg_error;
    assign entry_cfg_x_wd[i] = reg_wdata[2];

    assign entry_cfg_a_we[i] = addr_hit[ADDR_HIT_ENTRY_CFG_OFFSET + i] & reg_we & !reg_error;
    assign entry_cfg_a_wd[i] = reg_wdata[4:3];

    assign entry_cfg_sire_we[i] = addr_hit[ADDR_HIT_ENTRY_CFG_OFFSET + i] & reg_we & !reg_error;
    assign entry_cfg_sire_wd[i] = reg_wdata[5];

    assign entry_cfg_siwe_we[i] = addr_hit[ADDR_HIT_ENTRY_CFG_OFFSET + i] & reg_we & !reg_error;
    assign entry_cfg_siwe_wd[i] = reg_wdata[6];

    assign entry_cfg_sixe_we[i] = addr_hit[ADDR_HIT_ENTRY_CFG_OFFSET + i] & reg_we & !reg_error;
    assign entry_cfg_sixe_wd[i] = reg_wdata[7];

    assign entry_cfg_sere_we[i] = addr_hit[ADDR_HIT_ENTRY_CFG_OFFSET + i] & reg_we & !reg_error;
    assign entry_cfg_sere_wd[i] = reg_wdata[8];

    assign entry_cfg_sewe_we[i] = addr_hit[ADDR_HIT_ENTRY_CFG_OFFSET + i] & reg_we & !reg_error;
    assign entry_cfg_sewe_wd[i] = reg_wdata[9];

    assign entry_cfg_sexe_we[i] = addr_hit[ADDR_HIT_ENTRY_CFG_OFFSET + i] & reg_we & !reg_error;
    assign entry_cfg_sexe_wd[i] = reg_wdata[10];

    assign entry_user_cfg_we[i] = addr_hit[ADDR_HIT_ENTRY_USER_CFG_OFFSET + i] & reg_we & !reg_error;
    assign entry_user_cfg_wd[i] = reg_wdata[31:0];
  end

  logic   mdcfg_hit_vector, srcmd_en_hit_vector, srcmd_enh_hit_vector,
          entry_addr_hit_vector, entry_addrh_hit_vector, entry_cfg_hit_vector, entry_user_cfg_hit_vector;
  
  assign  mdcfg_hit_vector = (|addr_hit[(13 + N_MDS - 1):13]);
  assign  srcmd_en_hit_vector = (|addr_hit[(ADDR_HIT_SRCMD_EN_OFFSET + N_RRID - 1):ADDR_HIT_SRCMD_EN_OFFSET]);
  assign  srcmd_enh_hit_vector = (|addr_hit[(ADDR_HIT_SRCMD_ENH_OFFSET + N_RRID - 1):ADDR_HIT_SRCMD_ENH_OFFSET]);
  assign  entry_addr_hit_vector = (|addr_hit[(ADDR_HIT_ENTRY_ADDR_OFFSET + N_ENTRIES - 1):ADDR_HIT_ENTRY_ADDR_OFFSET]);
  assign  entry_addrh_hit_vector = (|addr_hit[(ADDR_HIT_ENTRY_ADDRH_OFFSET + N_ENTRIES - 1):ADDR_HIT_ENTRY_ADDRH_OFFSET]);
  assign  entry_cfg_hit_vector = (|addr_hit[(ADDR_HIT_ENTRY_CFG_OFFSET + N_ENTRIES - 1):ADDR_HIT_ENTRY_CFG_OFFSET]);
  assign  entry_user_cfg_hit_vector = (|addr_hit[(ADDR_HIT_ENTRY_USER_CFG_OFFSET + N_ENTRIES - 1):ADDR_HIT_ENTRY_USER_CFG_OFFSET]);

  // Read data return
  always_comb begin
    reg_rdata_next = '0;
    unique case (1'b1)
      addr_hit[0]: begin
        reg_rdata_next[23:0] = version_vendor_qs;
        reg_rdata_next[31:24] = version_specver_qs;
      end

      addr_hit[1]: begin
        reg_rdata_next[31:0] = implementation_qs;
      end

      addr_hit[2]: begin
        reg_rdata_next[1:0] = hwcfg0_mdcfg_fmt_qs;
        reg_rdata_next[3:2] = hwcfg0_srcmd_fmt_qs;
        reg_rdata_next[4] = hwcfg0_tor_en_qs;
        reg_rdata_next[5] = hwcfg0_sps_en_qs;
        reg_rdata_next[6] = hwcfg0_user_cfg_en_qs;
        reg_rdata_next[7] = hwcfg0_prient_prog_qs;
        reg_rdata_next[8] = hwcfg0_rrid_transl_en_qs;
        reg_rdata_next[9] = hwcfg0_rrid_transl_prog_qs;
        reg_rdata_next[10] = hwcfg0_chk_x_qs;
        reg_rdata_next[11] = hwcfg0_no_x_qs;
        reg_rdata_next[12] = hwcfg0_no_w_qs;
        reg_rdata_next[13] = hwcfg0_stall_en_qs;
        reg_rdata_next[14] = hwcfg0_peis_qs;
        reg_rdata_next[15] = hwcfg0_pees_qs;
        reg_rdata_next[16] = hwcfg0_mfr_en_qs;
        reg_rdata_next[23:17] = hwcfg0_md_entry_num_qs;
        reg_rdata_next[29:24] = hwcfg0_md_num_qs;
        reg_rdata_next[30] = hwcfg0_addrh_en_qs;
        reg_rdata_next[31] = hwcfg0_enable_qs;
      end

      addr_hit[3]: begin
        reg_rdata_next[15:0] = hwcfg1_rrid_num_qs;
        reg_rdata_next[31:16] = hwcfg1_entry_num_qs;
      end

      addr_hit[4]: begin
        reg_rdata_next[15:0] = hwcfg2_prio_entry_qs;
        reg_rdata_next[31:16] = hwcfg2_rrid_transl_qs;
      end

      addr_hit[5]: begin
        reg_rdata_next[31:0] = entryoffset_qs;
      end

      addr_hit[6]: begin
        reg_rdata_next[0] = err_cfg_lock_qs;
        reg_rdata_next[1] = err_cfg_ie_qs;
        reg_rdata_next[2] = err_cfg_rs_qs;
        reg_rdata_next[3] = err_cfg_msi_en_qs;
        reg_rdata_next[4] = err_cfg_stall_violation_en_qs;
        reg_rdata_next[18:8] = err_cfg_msidata_qs;
      end

      addr_hit[7]: begin
        reg_rdata_next[0] = err_info_v_qs;
        reg_rdata_next[2:1] = err_info_ttype_qs;
        reg_rdata_next[3] = err_info_msi_werr_qs;
        reg_rdata_next[7:4] = err_info_etype_qs;
        reg_rdata_next[8] = err_info_svc_qs;
      end

      addr_hit[8]: begin
        reg_rdata_next[31:0] = err_reqaddr_qs;
      end

      addr_hit[9]: begin
        reg_rdata_next[31:0] = err_reqaddrh_qs;
      end

      addr_hit[10]: begin
        reg_rdata_next[15:0] = err_reqid_rrid_qs;
        reg_rdata_next[31:16] = err_reqid_eid_qs;
      end

      addr_hit[11]: begin
        reg_rdata_next[31:0] = err_msiaddr_qs;
      end

      addr_hit[12]: begin
        reg_rdata_next[31:0] = err_msiaddrh_qs;
      end

      (mdcfg_hit_vector): begin
        for(int i = 0; i < N_MDS; i++) begin
          if (addr_hit[13 + i]) begin
            reg_rdata_next[15:0] = mdcfg_qs[i];
          end
        end
      end

      (srcmd_en_hit_vector): begin
        for(int i = 0; i < N_RRID; i++) begin
          if (addr_hit[ADDR_HIT_SRCMD_EN_OFFSET + i]) begin
            reg_rdata_next[0] = srcmd_en_lock_qs[i];
            reg_rdata_next[31:1] = srcmd_en_md_qs[i];
          end
        end
      end

      (srcmd_enh_hit_vector): begin
        for(int i = 0; i < N_RRID; i++) begin
          if (addr_hit[ADDR_HIT_SRCMD_ENH_OFFSET + i]) begin
            reg_rdata_next[31:0] = srcmd_enh_qs[i];
          end
        end
      end

      (entry_addr_hit_vector): begin
        for(int i = 0; i < N_ENTRIES; i++) begin
          if (addr_hit[ADDR_HIT_ENTRY_ADDR_OFFSET + i]) begin
            reg_rdata_next[31:0] = entry_addr_qs[i];
          end
        end
      end

      (entry_addrh_hit_vector): begin
        for(int i = 0; i < N_ENTRIES; i++) begin
          if (addr_hit[ADDR_HIT_ENTRY_ADDRH_OFFSET + i]) begin
            reg_rdata_next[31:0] = entry_addrh_qs[i];
          end
        end
      end

      (entry_cfg_hit_vector): begin
        for(int i = 0; i < N_ENTRIES; i++) begin
          if (addr_hit[ADDR_HIT_ENTRY_CFG_OFFSET + i]) begin
            reg_rdata_next[0] = entry_cfg_r_qs[i];
            reg_rdata_next[1] = entry_cfg_w_qs[i];
            reg_rdata_next[2] = entry_cfg_x_qs[i];
            reg_rdata_next[4:3] = entry_cfg_a_qs[i];
            reg_rdata_next[5] = entry_cfg_sire_qs[i];
            reg_rdata_next[6] = entry_cfg_siwe_qs[i];
            reg_rdata_next[7] = entry_cfg_sixe_qs[i];
            reg_rdata_next[8] = entry_cfg_sere_qs[i];
            reg_rdata_next[9] = entry_cfg_sewe_qs[i];
            reg_rdata_next[10] = entry_cfg_sexe_qs[i];
          end
        end
      end

      (entry_user_cfg_hit_vector): begin
        for(int i = 0; i < N_ENTRIES; i++) begin
          if (addr_hit[ADDR_HIT_ENTRY_USER_CFG_OFFSET + i]) begin
            reg_rdata_next[31:0] = entry_user_cfg_qs[i];
          end
        end
      end

      default: begin
        reg_rdata_next = '1;
      end
    endcase
  end

  logic [$clog2(N_ENTRIES) - 1 : 0] entry_idx_d, entry_idx_q, entry_idx2_q;
  logic  rcfg_entry, rcfg_entry_q, rcfg_entry2_q;
  entry_t entry_data_q, entry_data_d;

  assign rcfg_entry = |entry_addr_we || |entry_addrh_we || 
                      |entry_cfg_r_we || |entry_cfg_w_we || |entry_cfg_x_we ||
                      |entry_cfg_a_we || |entry_cfg_sire_we || |entry_cfg_siwe_we ||
                      |entry_cfg_sixe_we || |entry_cfg_sere_we || |entry_cfg_sewe_we;

  always_comb begin
    entry_idx_d = '0;

    // Assess which entry to reconfigure
    if ( rcfg_entry ) begin
      for(int i = 1; i < N_ENTRIES - 1; i++) begin
        if (is_entry_addr_hit(i)) begin
          entry_idx_d = i;
          break;
        end
      end
    end
  end

  always_ff @(posedge clk_i or negedge rst_ni) begin
    if (!rst_ni) begin
      entry_idx_q <= 1;
      entry_idx2_q <= 1;

      rcfg_entry_q <= 1'b0;
      rcfg_entry2_q <= 1'b0;
    end else begin
      entry_idx_q <= entry_idx_d;
      entry_idx2_q <= entry_idx_q;

      rcfg_entry_q <= rcfg_entry;
      rcfg_entry2_q <= rcfg_entry_q;

      if(rcfg_entry_q) begin
        entry_data_q = entry_data_d;
      end
    end
  end
  
  assign valid_o = rcfg_entry2_q;
  assign entry_idx_o = entry_idx2_q;
  assign entry_data_o = entry_data_q;

  assign entry_data_d.addr.base_addr = {reg2hw.entry_addrh[entry_idx_q], reg2hw.entry_addr[entry_idx_q]};
  assign entry_data_d.addr.end_addr  = '0;
  assign entry_data_d.cfg            = reg2hw.entry_cfg[entry_idx_q];

  // Unused signal tieoff

  // wdata / byte enable are not always fully used
  // add a blanket unused statement to handle lint waivers
  logic unused_wdata;
  logic unused_be;
  assign unused_wdata = ^reg_wdata;
  assign unused_be = ^reg_be;

  // Assertions for Register Interface
  `ASSERT(en2addrHit, (reg_we || reg_re) |-> $onehot0(addr_hit))

endmodule
